// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/jhinmainksta/habr-clone/graph/my_model"
)

type Mutation struct {
}

type NewComment struct {
	Content  string `json:"content"`
	PostID   int    `json:"postID"`
	UserID   int    `json:"userID"`
	ParentID *int   `json:"parentID,omitempty"`
}

type NewPost struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	UserID  int    `json:"userID"`
	Blocked *bool  `json:"blocked,omitempty"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Post struct {
	ID       string              `json:"id"`
	Title    string              `json:"title"`
	Content  string              `json:"content"`
	UserID   int                 `json:"userID"`
	Blocked  *bool               `json:"blocked,omitempty"`
	Comments []*my_model.Comment `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}
